version: '3'

networks:
  bibbox-default-network:
    external: true
    
services:
  postgres:
    image: postgres:13-alpine
    networks:
      - bibbox-default-network
    environment:
      - POSTGRES_USER=molgenis
      - POSTGRES_PASSWORD=molgenis
      - POSTGRES_DB=molgenis
    ports:
      - "5433:5433"
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'
    
  emx2:
    image: molgenis/molgenis-emx2
    networks:
      - bibbox-default-network
    restart: unless-stopped
    environment:
      - MOLGENIS_POSTGRES_URI=jdbc:postgresql://postgres/molgenis
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: on-failure

